### ISSUE TITLE
Create the release 1.0.0

### ISSUE THREAD

**Issue by j-rivero** [ros/urdfdom_headers#29]
I believe that after the merge of pull request #23 we are ready to tag and release the version 1.0.0.

If there is anything missing, please let me know.

//cc @scpeters

**Comment by scpeters** [comment]
+1

**Comment by scpeters** [comment]
Here's a draft release:

* https://github.com/ros/urdfdom_headers/releases/tag/untagged-3ecc9e0d7712be4f37d3

how does it look?

**Comment by j-rivero** [comment]
I can not see that URL, 404 for my user :(

**Comment by scpeters** [comment]
hm...

**Comment by scpeters** [comment]
ok, I just released it anyway:

* https://github.com/ros/urdfdom_headers/releases/tag/1.0.0

**Comment by progtologist** [comment]
I am bumping this, well, 18 months later, because this is causing troubles with urdf. 
Versioning in urdfdom_headers appears to be sketchy at least. 
Version 1.0.0 was set on Mar 17 while Version 0.4.2 was set on Jul 6 with a rewritten history.
This by itself wouldn't actually cause problems, but [this](https://github.com/ros/urdf/blob/kinetic-devel/urdf/urdfdom_compatibility.h.in) autogenerated header in urdf depends on the versioning scheme to function properly, and well... it doesn't.

**Comment by scpeters** [comment]
The commit history does look a bit confusing:

* https://github.com/ros/urdfdom_headers/commits/master

I bumped the version to 1.0.0 in 9aed7256e06d62935966de2a9bc9ddfac96e7a85 (March 16, 2016), but that was on the scpeters:unboost branch in #23, which wasn't merged into master until July 20, 2016 (5cb0b6b6a99eeeff5cd111dabd0093a29305a2f9). Shortly before that on July 5, we bumped the version to 0.4.2 (76da8dc92928b8a1e834337e2026d32bd8b54de8).

So the commit history is a little confusing, but I'm pretty sure we didn't rewrite any history.

**Comment by progtologist** [comment]
@scpeters this seems to be the issue, however at some time in the past, 9aed725 must have pointed to 0.4.2, because back in 2016 I was able to compile ROS for RPi using the same instructions. 

Anyway, I will update the Raspberry Pi installation guide to reflect to the correct commit and add a few more workarounds that I discovered yesterday while compiling.

Thanks for your immediate response.
